language: ruby
cache: bundler
dist: xenial

before_install:
  - pwd
  - sudo apt-get install -y graphviz python-pip libyajl2 cmake build-essential
  - sudo apt-get install -y libgflags-dev
  - sudo apt-get install -y libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev
  - gem install camtool
  - git clone https://github.com/facebook/rocksdb.git
  - cd rocksdb
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install INSTALL_PATH=/usr
  - cd ..
  - git clone https://github.com/crimson-unicorn/parsers.git
  - cd parsers/cdm/ProvParser
  - sudo pip install .
  - cd ../../../
  - ls
  - pwd

script:
  - make validate

notifications:
  slack: camflow:T3Umf9cAIwKnaxFEkjeZV7RM
