language: ruby
cache: bundler
dist: xenial

before_install:
  - sudo apt-get install -y graphviz python-pip libyajl2 cmake build-essential
  - sudo apt-get install -y libgflags-dev
  - sudo apt-get install -y libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev
  - gem install camtool
  - git clone -b 'v5.17.2' --single-branch --depth 1 https://github.com/facebook/rocksdb.git
  - cd rocksdb
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install INSTALL_PATH=/usr
  - cd ..
  - git clone https://github.com/crimson-unicorn/parsers.git
  - cd parsers/cdm/ProvParser
  - sudo python setup.py install
  - cd /home/travis/build/CamFlow/example-datasets/

script:
  - make validate

notifications:
  slack: camflow:T3Umf9cAIwKnaxFEkjeZV7RM
